#!/usr/bin/env sh

COLORS=" --color=fg:-1,bg:-1,hl:#5f87af \
 --color=fg+:-1,bg+:-1,hl+:#87ff00 \
 --color=info:-1,prompt:#5fd7ff,pointer:#87ff00 \
 --color=marker:-1,spinner:#525252,header:#424242"

SESSION=`tmux display-message -p 'session#I'`

#TREE="fzf $COLORS --bind \"enter:execute(echo eval -client client0 edit '{}' | kak -p $SESSION)\" --reverse"

FZF_DEFAULT_COMMAND='rg'

TREE="~/tree $SESSION"
EDITOR="kak -s $SESSION"

tmux split-window -h -l 75%
tmux send-keys -t 1 "$EDITOR" C-m
tmux split-window -v -l 20%
tmux select-pane -t 2 -P 'fg=colour255,bg=colour234'

sleep 0.1

tmux send-keys -t 0 "$TREE" C-m
